- name: Transfer and upload CSV file
  hosts: your_target_host
  tasks:
    - name: Copy CSV file to the remote host
      copy:
        src: "/C:/Users/Vicky/Documents/reports_20231019_latam-it-operations.202310191333.chubb-linux-standards.ouput.csv"
        dest: "/tmp/reports.csv"
    - name: Use curl to upload the file
      command: curl --location 'http://abc.com/playbook_enforcement' --form "file=@/tmp/reports.csv"
      register: curl_output
    - name: Display curl output
      debug:
        var: curl_output.stdout
