- name: Upload file using Ansible
  hosts: all
  tasks:
    - name: Upload file
      uri:
        url:  http://192.168.1.6:8080/playbook_enforcement
        method: POST
        body_format: form-multipart
        body:
          file:
            src: "/C:/Users/Vicky/Documents/reports_20231019_latam-it-operations.202310191333.chubb-linux-standards.ouput.csv"
            mode: "0644"
