- name: Upload file using Ansible
  hosts: localhost
  tasks:
    - name: Upload file
      shell: >
        curl --location 'http://192.168.1.6:8080/playbook_enforcement'
        --form 'file=@"/home/osboxes/reports_20231019_latam-it-operations.202310191333.chubb-linux-standards.ouput.csv"'
